name: Setup OSS
description: Setup OSS

runs:
  using: "composite"
  steps:
    - name: Install ossutil
      run: "sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash"
      shell: bash

    - name: Write ossutil config
      run: echo ${{ secrets.OSSUTIL_CONFIG }} >> "./.ossutilconfig"
      shell: bash
