name: Prune unused files

on:
  workflow_dispatch:

jobs:
  prune:
    runs-on: ubuntu-latest
    concurrency:
      group: prune-oss-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup OSS
        uses: ./.github/actions/setup-oss
        with:
          ossutil-config: ${{ secrets.OSSUTIL_CONFIG }}

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build Dist
        run: pnpm run build

      - name: Remove files
        run: pnpm run prune
